/*
 * generated by Xtext 2.20.0
 */
package com.eclipsesource.workflow.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WorkflowAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/eclipsesource/workflow/dsl/parser/antlr/internal/InternalWorkflow.tokens");
	}
}
