/*
 * generated by Xtext 2.12.0
 */
package com.eclipsesource.workflow.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WorkflowRuntimeModule extends AbstractWorkflowRuntimeModule {
}
