/*
 * generated by Xtext 2.12.0
 */
package com.eclipsesource.workflow.dsl.ui

import org.eclipse.ui.plugin.AbstractUIPlugin

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
class WorkflowUiModule extends AbstractWorkflowUiModule {
	
	new(AbstractUIPlugin plugin) {
		super(plugin)
	}
	
}
