apiVersion: v1
kind: Service
metadata:
  labels:
    app: coffee-editor
  name: theia
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: coffee-editor
  sessionAffinity: None
  type: LoadBalancer

