apiVersion: v1
kind: Service
metadata:
  name: coffee-editor-demo-service
  labels:
    app: coffee-editor
  namespace: coffee
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 3000
  selector:
    app: coffee-editor
  sessionAffinity: None
  type: LoadBalancer

