/*
 * generated by Xtext 2.12.0
 */
package com.eclipsesource.workflow.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WorkflowStandaloneSetup extends WorkflowStandaloneSetupGenerated {

	def static void doSetup() {
		new WorkflowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
