/*
 * generated by Xtext 2.12.0
 */
package com.eclipsesource.workflow.dsl.ide

import com.eclipsesource.workflow.dsl.ide.^extension.CommandService
import org.eclipse.xtext.ide.server.commands.IExecutableCommandService

/**
 * Use this class to register ide components.
 */
class WorkflowIdeModule extends AbstractWorkflowIdeModule {
	
	def Class<? extends IExecutableCommandService> bindIExecutableCommandService() {
		return CommandService
	}
}
