/*
 * generated by Xtext 2.12.0
 */
package com.eclipsesource.workflow.dsl.scoping

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class WorkflowScopeProvider extends AbstractDeclarativeScopeProvider {
}
