/*
 * generated by Xtext 2.20.0
 */
package com.eclipsesource.workflow.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWorkflowScopeProvider extends DelegatingScopeProvider {
}
