/*
 * generated by Xtext 2.17.1
 */
package com.eclipsesource.workflow.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWorkflowScopeProvider extends DelegatingScopeProvider {
}
